name: AwsEC2

on:

  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Start AWS EC2

        run: |
          aws ec2 start-instances --instance-ids ${{secrets.AWS_INSTANCE_ID }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

      - name: SSH connect
        uses: appleboy/ssh-action@master
        with:
            host: ${{ secrets.AWS_INSTANCE_IP }}
            username: ${{ secrets.AWS_INSTANCE_USER }}
            key: ${{ secrets.AWS_SSH_KEY_PEM }}
            port: ${{ secrets.AWS_INSTANCE_SSH_PORT }}
            script: | 
              sudo rm -rf ~/${{ github.event.repository.name }}
              mkdir -p ~/${{ github.event.repository.name }}
              sudo chmod 7777 ~/${{ github.event.repository.name }}
              cd ~/${{ github.event.repository.name }}
              sudo wget https://raw.githubusercontent.com/luiz0067yahoo/boracomer/main/Dockerfile
              sudo docker build -t ${{ github.event.repository.name }} .
              sudo docker run -d -p 80:80 ${{ github.event.repository.name }}
