              #git config --global user.email "${GH_USERNAME}@users.noreply.github.com"
              #git config --global user.name "${GH_USERNAME}"

              #sudo wget https://raw.githubusercontent.com/${{ github.actor }}/${{ github.event.repository.name }}/main/Dockerfile /home/${{ secrets.AWS_INSTANCE_USER }}/${{ github.event.repository.name }}/Dockerfile
              sudo wget https://raw.githubusercontent.com/${{ github.actor }}/${{ github.event.repository.name }}/master/Dockerfile /home/${{ secrets.AWS_INSTANCE_USER }}/${{ github.event.repository.name }}/Dockerfile
              echo "download Dockerfile"
              cat /home/${{ secrets.AWS_INSTANCE_USER }}/${{ github.event.repository.name }}/Dockerfile

              
              docker stop container_${{ github.event.repository.name }} 
              echo "stop container"
              docker kill container_${{ github.event.repository.name }} 
              echo "kill container"
              docker rm container_${{ github.event.repository.name }} 

              sudo docker build -t ${{ github.event.repository.name }} .
              echo "build container"
              
              
              docker run -d --name container_${{ github.event.repository.name }} --rm -p ${{ secrets.APP_PORT }}:${{ secrets.APP_PORT }} -ti ${{ github.event.repository.name }}
              #sudo docker run -d -p ${{ secrets.APP_PORT }}:${{ secrets.APP_PORT }} ${{ github.event.repository.name }} 
              echo "run container"

              #sudo docker exec –it container_${{ github.event.repository.name }} /bin/bash
              #sudo  docker run -d -p 3000:3000 demo_cms_rails
              #docker run --name pandora_community --rm \
              #-p 8085:80 \
              #-p 41121:41121 \
              #-p 162:162 \
              #-e DBHOST=mysqlhost.local \
              #-e DBNAME=pandora \
              #-e DBUSER=pandora \
              #-e DBPASS=pandora \
              #-e DBPORT=3306 \
              #-e SLEEP=5 \
              #-e RETRIES=3 \
              #-e INSTANCE_NAME=pandora_community \
              #-ti rameijeiras/pandorafms-community:740
              #docker run -d --name container-name alpine watch "date >> /var/log/date.log"
